version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/jest/
            npm test > ~/test-results/jest/results.txt
          when: always
      - store_artifacts:
          path: /test-results/results.txt
          destination: /test-results
      - store_test_results:
          path: /test-results