version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - run: npm install 
      - run: npm test
      - store_test_results:
          path: /test-results
      - run:
          name: Make artifact directories
          command: |
            mkdir -p /test-results/
      - store_artifacts:
          path: /test-results/results.xml
          destination: /test-results
      - store_test_results:
          path: /test-results