version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: |
            mkdir -p ./test-results
            npm test --ci --reporters=jest
          when: always

      - store_artifacts:
          path: ./test-results/junit
          #destination: test-results
      - store_test_results:
          path: ./test-results