version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    working_directory: ~/repo
    
    steps:
      - checkout
      - run: npm install
      - run: npm ci

      # First we save the split test file names into an env
      # Then we pass that to jest
      - run:
          name: Run Jest tests using test splitting
          command: |
            TESTFILES=$(circleci tests glob "test/**/*.test.js" | circleci tests split --split-by=timings)
            npm test $TESTFILES

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
          destination: test_results