version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - run: npm install 
      - run: npm test
      - store_test_results:
          path: ~/test-results/jest