version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - run: npm install package.json
      - run:
          name: Run Tests
          command: |
            mkdir -p ./test-results
            yarn test --ci --reporters=jest-junit
          when: always

      - store_artifacts:
          path: ./test-results/results.txt
          destination: test-results
      - store_test_results:
          path: ./test-results