version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Jest tests using test splitting
          command: |
            TESTFILES=$(circleci tests glob "test/*.test.js" | circleci tests split --split-by=timings)
            npm test $TESTFILES

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
          destination: test_results