version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - run: npm install
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results
            npm test > ~/test-results/results.txt
            ~/test-results/results.txt
          when: always

      - store_artifacts:
          path: ~/test-results/results.txt
          destination: artifact-file
      - store_test_results:
          path: ~/test-results/results.txt