version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - run: npm install 
      - run: npm test
      - store_test_results:
          path: /test-results
      - run:
          name: Make artifact directories
          command: |
            mkdir -p /test-results/
      - run:
          name: Run Unit Tests
          command: |
            /opt/Unity/Editor/Unity - quit -batchmode -nographics -silent-crashes -logFile /dev/stdout -projectPath ./Source/ -runTests -testResults /test-results/results.xml
          working_directory: ~/project/
      - store_artifacts:
          path: /test-results/results.xml
          destination: /test-results
      - store_test_results:
          path: /test-results